# pytorch中tensor的形状改变
## 数据处理或者nn模型传播中，经常需要修改模型shape，这里总结下：

In [15]:
import torch
M = torch.tensor([[[1,1,1,1],
                   [2,2,2,2],
                   [3,3,3,3]],
                  [[4,4,4,4],
                   [5,5,5,5],
                   [6,6,6,6]]])
print(M)
print(M.shape)

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]])
torch.Size([2, 3, 4])


### 1. transpose()  （tensor转置）
将两个纬度调换，一次只能操作两个维度。

In [16]:
M1 = M.transpose(0,2)  # 将第0和第2维调换
print(M1)
print(M1.shape)
M2 = M.transpose(1,2)  # 将1，2维调换
print(M2)
print(M2.shape)

tensor([[[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]]])
torch.Size([4, 3, 2])
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 4, 3])


### 2. permute()  （多维度调换）
能一次性调换多个维度，但是必须传入所有维度。

In [22]:
M3 = M.permute(2,1,0)
print(M3)
print(M3.shape)

tensor([[[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]]])
torch.Size([4, 3, 2])


### 3. view() （不能用来转置）
view可以更改tensor形状，但是会改变顺序，所以不能用来转置。  
注意：view不能处理非连续的tensor，例如之前的M3

In [25]:
# 这段代码会报错
M4 = M3.view(3,4,2)
print(M4)
print(M4.shape)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [28]:
# 因为M3不是连续的
print(M3.is_contiguous())
# 所以正确的用法是
M4 = M3.contiguous().view(3,4,2)
print(M4)
print(M4.shape)

False
tensor([[[1, 4],
         [2, 5],
         [3, 6],
         [1, 4]],

        [[2, 5],
         [3, 6],
         [1, 4],
         [2, 5]],

        [[3, 6],
         [1, 4],
         [2, 5],
         [3, 6]]])
torch.Size([3, 4, 2])


### 4. reshape() （不能用来转置）
reshape可以理解为，先contiguous再view

In [30]:
M5 = M3.reshape(3,4,2) 
print(M5)
print(M5.shape)

tensor([[[1, 4],
         [2, 5],
         [3, 6],
         [1, 4]],

        [[2, 5],
         [3, 6],
         [1, 4],
         [2, 5]],

        [[3, 6],
         [1, 4],
         [2, 5],
         [3, 6]]])
torch.Size([3, 4, 2])
